### ISSUE TITLE
关于OPENVPN 怎么报错怎么解决

### ISSUE THREAD

**Issue by alroyso** [ftao/vpn-deploy-playbook#115]
fatal: [vpn.saiweivpn.com] => {'msg': "AnsibleError: Failed to template {{ lookup('file', inventory_dir + '/cred/openvpn/server.key') }}: could not locate file in lookup: /root/vpn-deploy-playbook/cred/openvpn/server.key", 'failed': True}
fatal: [vpn.saiweivpn.com] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "AnsibleError: Failed to template {{ lookup('file', inventory_dir + '/cred/openvpn/server.key') }}: could not locate file in lookup: /root/vpn-deploy-playbook/cred/openvpn/server.key", 'failed': True}]}

**Comment by ftao** [comment]
你跑的哪个playbook ,  openvpn 部分缺失缺少维护。 

我的经验基本openvpn 马上会被检测到.

**Comment by alroyso** [comment]
- openvpn
    - nat
    - role: ocserv

vpn.yml 里面的

**Comment by alroyso** [comment]
安装OPENVPN的时候 E: 未发现软件包 certified 这个没有找到怎么办呀？

**Comment by ftao** [comment]
certified 应该是这个role 去安装的， 你看看是否你的系统不支持。 
https://github.com/ftao/vpn-deploy-playbook/tree/master/roles/ftao.certified

openvpn 部分好久没动， 我现在也不知道了， 需要有空的的时候重新整理一下了。

**Comment by alroyso** [comment]
An ansible role to install certified in unbuntu/debian server .  上面写的是支持的，我是debian7.0的系统的，

**Comment by ftao** [comment]
你是在跑 openvpn-server.yml 这个playbook 是吧？ 
目前我这里可用的正常的openvpn 的设置方法是， 手工先将证书生成好， 然后用 openvpn 这个role . 
自动化的应该是上次有尝试一些， 但是没有完全完成， 所以可能有各种问题。 

配置如下， 
```
openvpn_use_radius: true
openvpn_radius_servers: "{{ radius_servers }}"
openvpn_cred:
  ca: "{{ lookup('file', inventory_dir + '/cred/openvpn/ca.crt') }}"
  cert: "{{ lookup('file', inventory_dir + '/cred/openvpn/server.crt') }}"
  key: "{{ lookup('file', inventory_dir + '/cred/openvpn/server.key') }}"
  dh: "{{ lookup('file', inventory_dir + '/cred/openvpn/dh1024.pem') }}"
```
