### ISSUE TITLE
proxy-backend.yml 这个group好像有点问题

### ISSUE THREAD

**Issue by vmlinz** [ftao/vpn-deploy-playbook#124]
- 设置 group variable

```
---
#default vars for proxy-backend


shadowsocks_servers:

  default:
    port: "38080"
    password: "nS42vGBqnZ7cWyntv"
    enable_udp: true

  udp_relay:
    port: "38081"
    password: "nS42vGBqnZ7cWyntv"
    enable_udp: true
```

- 然后运行`ansible-playbook proxy-backend.yml -l localhost -K -b`

- 结果，port的设置一直都是roles里面定义的default值，port : 5351

我正在看怎么打印group变量，等有进一步信息再做更新
