### ISSUE TITLE
用 Travis CI 测试 playbook/roles 语法

### ISSUE THREAD

**Issue by lexrus** [ftao/vpn-deploy-playbook#29]
Hi ftao,

我照葫芦画瓢，在我的[另一个 playbook 仓库](https://github.com/lexrus/ios-dev-playbook)里加了一个 `.travis.yml` 文件，然后在 [Travis CI](https://travis-ci.org) 开启了项目的集成测试，这样我本地可以省去测试语法的过程，新的 pull request 还会在 comment 里收到 Travis 发出的编译结果。我觉得项目慢慢变大的时候需要这种质量控制工具，所以大概写了一个 vpn-deploy-playbook 用的 `.travis.yml`，你看有没有必要用上。

理论上可以把所有 playbook 全跑一遍，但是 Travis 测试机的内存可能不够，所以只测了语法。

.travis.yml

``` yaml

---
language: python
python: "2.7"

before_install:

  # Remove MySQL.
  - sudo apt-get -y purge 'mysql*'
  - sudo apt-get -y autoremove
  - sudo apt-get -y autoclean
  - sudo rm -rf /var/lib/mysql
  - sudo truncate -s 0 /var/log/mysql/error.log

  - sudo apt-get update

install:

  # Install Ansible.
  - pip install ansible

script:

  # Check the role/playbook's syntax.
  - >
    ansible-playbook -i ansible_hosts.local *.yml --syntax-check
    | grep -q 'ERROR'
    && (echo 'Test: fail' && exit 1)
    || (echo 'Test: pass' && exit 0)

  # Run the role/playbook with ansible-playbook.
  # - ansible-playbook -i ansible_hosts.local 022_shadowsocks.yml -c local --sudo --skip-tags sysctl

  # Requests to make sure web respond.
  # - "curl --retry 3 --connect-timeout 5 --max-time 120 -s -o /dev/null http://localhost/"
```
