### ISSUE TITLE
proxy-backend 报错

### ISSUE THREAD

**Issue by lexrus** [ftao/vpn-deploy-playbook#60]
Ubuntu 14.04.

```
TASK: [ss-server | add shadowsocks repo] ************************************** 
failed: [localhost] => {"failed": true, "item": ""}
msg: Could not import python modules: pycurl. Please install python-pycurl package.
```

**Comment by ftao** [comment]
这个是 ansible apt_repo    需要 pycurl,    在common 里面加一个就可以了。https://github.com/ftao/vpn-deploy-playbook/commit/0dac55720d63dc7c31974895a6b4c80d8c0e726e  
似乎这个改过之后，之后的步骤还是有不对。 可能 shadowsocks-libev 那一块可能和最新版本不一致了。

**Comment by lexrus** [comment]
用 python 版装的话，好像也有问题了。

**Comment by ftao** [comment]
这个模式的话需要 libev 版本， 因为需要 UDP 模式。 
我又push 了一次， 用下面的配置可以跑通了。 
```
shadowsocks_provider: 'libev'
shadowsocks_servers:
  default:
    port: 8838
    password: "some-password"
  udp_relay:
    port: 8839
    password: "some-password"
    enable_udp: true
```

这个playbook 原来是用来架设通过国内中转的VPN 的服务器， 不过缺点挺大的， 就是处理 53 端口的DNS 特殊处理了， 其他UDP 通讯都不正常的。 

现在我国内中转的VPN 服务， 国内和国外VPN 之间通讯用  static-key  openvpn 模式的， 目前来说挺稳定的。  有空我把配置放上来。
