### ISSUE TITLE
[ppp-radiusclient | Enforce radiusclient is installed]

### ISSUE THREAD

**Issue by alroyso** [ftao/vpn-deploy-playbook#64]
验证客户端，跳过的问题，这个要怎么解决呀？

TASK: [ppp-radiusclient | Enforce radiusclient is installed] ****************** 
skipping: [host1]

TASK: [ppp-radiusclient | upload radiusclient config] ************************* 
skipping: [host1] => (item=radiusclient.conf)
skipping: [host1] => (item=servers)
skipping: [host1] => (item=dictionary)

TASK: [ppp-radiusclient | fix can't resolve own hostname problem  - hostname] *** 
skipping: [host1]

TASK: [ppp-radiusclient | fix can't resolve own hostname problem - fqdn] ****** 
skipping: [host1]

**Comment by ftao** [comment]
这个不是一个错误， 只是说没有启用  通过radius 服务器认证的功能。 
下面这个文档的配置就是不启用的， 如果你的服务器只是给自己／或者很少的几个人用的， 可以不用raidus 的。 
https://github.com/ftao/vpn-deploy-playbook/wiki/%E9%85%8D%E7%BD%AEPPTP-VPN%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by alroyso** [comment]
你好，host_vars/我是在这里配置变量。

![Uploading 1.png…]()

**Comment by alroyso** [comment]
pptp_use_radius: true
pptp_radius_servers:
   - host: 222.73.47.161:16450
     secret: 123

**Comment by alroyso** [comment]
但是也是不被启动，这是配置有问题还是 环境变量要配置？   请指点下。

**Comment by ftao** [comment]
host_vars/xxx 的文件名和 ansible_hosts 中的主机名要一致的。否则不会被读取。

**Comment by alroyso** [comment]
还有个问题，验证IP 跟端口是多个，  比如ip:16450   ip:16456

pptp_radius_servers:

host: IP:16450 
secret: 123
host: IP:16456
secret: 123

那么这个格式是这样写的吗？

**Comment by ftao** [comment]
使用 YAML 文件中列表的的写法， 请自行google 。 
另外你贴代码的时候用一下markdown 语法， 没发现格式都是乱的吗？

**Comment by alroyso** [comment]
pptp_use_radius: true
pptp_radius_servers:
        - host: IP:16450 
         secret: 123
       - host: IP:16456
         secret: 123


这样是对代码？  多个服务器配置的话？

**Comment by ftao** [comment]
`IP:16450`    要改成完整的IP 就可以了。

**Comment by alroyso** [comment]
验证客户端买有对win平台的字典吗？

**Comment by ftao** [comment]
不明白你的意思。 之前搭建的服务器， window 系统的客户端可以连上VPN，验证通过的。

**Comment by alroyso** [comment]
我这里老是鉴定失败

**Comment by alroyso** [comment]
radiusclient   这个怎么使用调试模式啊?

**Comment by ftao** [comment]
失败， 你要看  pptpd 的日志。  打开调试也是打开pptpd 的日志 ｀/etc/pptpd.conf` . 
同时你要去看 radius 服务器的日志是什么情况。

**Comment by alroyso** [comment]
我找到原因了   我使用直接IP 就可以验证通过，但是用ip:16450  这样的方式就无法通过，  这个验证是不能这样写的吗？

**Comment by alroyso** [comment]
因为我这里是多台验证服务器，有的服务器 是换了端口的。

**Comment by ftao** [comment]
那很可能是没有支持自定义端口的情况， 可能配置文件格式生成的就不对了。 
这确实是一个bug .

**Comment by alroyso** [comment]
o .

**Comment by alroyso** [comment]
谢谢了

**Comment by ftao** [comment]
bug 现在应该已经修正， 支持指定自定义的port 了。 

请配置如下变量
  ```
  pptp_use_radius: true
  pptp_radius_servers:
    - host:  ip.of.radius-server-1   #请填写radius 服务器的IP 地址或者域名
      secret: some-radius-secret   #请填写radius 服务器的密钥                                                                
    - host:  ip.of.radius-server-2 
      auth_port: 5678               #如果服务器使用自定义的端口，请配置auth_port 和 acct_port 
      acct_port: 5679
      secret: some-radius-secret     
  ```

**Comment by alroyso** [comment]
fatal: [vpn] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'radius_servers' is undefined", 'failed': True}
fatal: [vpn] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'radius_servers' is undefined", 'failed': True}]}

FATAL: all hosts have already failed -- aborting

请问这个问题是什么原因造成的?

我用的vpn.yml  在group_vars/vpn.yml

**Comment by alroyso** [comment]
radius_servers:
  - host: 222.73.47.179
    auth_port: 16450
    acct_port: 16460
    secret: 123
  - host: 222.73.47.161
    secret: 123

ipsec_enable_ikev1: true
ipsec_enable_ikev2: true
ipsec_enable_l2tp: true
ipsec_use_radius: true
ipsec_radius_servers: "{{ radius_servers }}"
ipsec_psk: "123456"
ipsec_gen_ios8_profile: false

pptp_network:
  - local_ip: 172.0.0.1
  - remote_ip: 172.0.0.2-172.255.255.255
  - subnet: 172.0.0.0/8
  - mtu: 1340

pptp_use_radius: true
pptp_radius_servers: "{{ radius_servers }}"
pptp_dns_servers:
  - 8.8.4.4
  - 8.8.8.8


l2tp_network:
  - local_ip: 172.0.0.1
  - remote_ip: 172.0.0.2-172.255.255.255
  - subnet: 172.0.0.0/8

l2tp_under_ipsec: true
l2tp_use_radius: true
l2tp_radius_servers: "{{ radius_servers }}"

l2tp_dns_servers:
  - 8.8.4.4
  - 8.8.8.8

ocserv_use_radius: True
ocserv_radius_servers: "{{ radius_servers }}"
ocserv_cert_auto: true

group_vars/vpn.yml  格式如上  ，

**Comment by ftao** [comment]
ansible_hosts 文件怎么写的？  如果你用 group_vars/vpn.yml 配置的话， 需要把  对应主机加入到  vpn 组里面。 类似这样在ansible_hosts 这样写
```yaml
your-host-name  

[vpn]
your-host-name
```

**Comment by alroyso** [comment]
server1  ansible_ssh_host=23.88.228.166 ansible_connection=ssh ansible_ssh_user=root ansible_ssh_pass=passwd ansible_sudo=true
[vpn]
server1

这样写的。是否正确、 我是在/etc/ansible/hosts 配置的

**Comment by alroyso** [comment]
pptp_network:
   - local_ip: 172.0.0.1
   - remote_ip: 172.0.0.2-172.255.255.255
   - subnet: 172.0.0.0/8
   - mtu: 1340   

你好，找到原因了，这样配置报错  不能在外面添加这个内网IP吗？

**Comment by ftao** [comment]
yaml 格式问题。 请参考  https://github.com/ftao/vpn-deploy-playbook/blob/master/roles/pptp/defaults/main.yml  
```
pptp_network:
   - local_ip: 172.0.0.1
   - remote_ip: 172.0.0.2-172.255.255.255
   - subnet: 172.0.0.0/8
   - mtu: 1340   
```
这种写法变成列表了。   不是字典。
