### ISSUE TITLE
Wiki entry/explanation for shadowsocks

### ISSUE THREAD

**Issue by cc2001** [ftao/vpn-deploy-playbook#71]
I don't understand the Shadowsocks setup. Can you add a quick wiki entry explaining how to set it up?

- Why is there a proxy-frontend and a proxy-backend? Don't you just need 1 shadowsocks server?
- Is proxy-frontend supposed to be a China domestic server, and proxy-backend an offshore server?
- Is it possible to make Shadowsocks authenticate with Radius?

Thank you

**Comment by ftao** [comment]
> - Why is there a proxy-frontend and a proxy-backend? Don't you just need 1 shadowsocks server?

It is complex & out-of-dated setup , don't use it ,  I plan to rewrite them . 

> - Is proxy-frontend supposed to be a China domestic server, and proxy-backend an offshore server?

yes 

> - Is it possible to make Shadowsocks authenticate with Radius?
no 

for  simple shadowsocks server , just use proxy-backend  , or a more simple playbook like 
```
---
- hosts: all
  roles:
    - common
    - role: ss-server
      name: "default"
      port: 6789
      password: "some-really-long-password"
```

I will  add a wiki later .
